version: 0.1
            
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/webinar-demo-0.0.1-SNAPSHOT.war
  discard-paths: yes
